export enum Commands {
    HELP = "help",
    REGISTER = "register",
    UNREGISTER = "unregister",
    RECENT_STATS = "rs",
    TOGGLE_AUTO = "toggleauto",
    GPAT = "gpat",
    GPAT_CLEAR = "gpatclear",
    CAOW = "caow",
    STORY = "story",
    TURBO_LEADERBOARD = "turbolb",
    TURBO_STATS = "turbostats",
    TURBO_PAIRINGS = "turbopairs",
    MY_TURBO_PAIRINGS = "myturbopairs",
    TOGGLE_SHARED_CONTEXT = "togglesharedcontext",
    PROFILE = "profile",
    TOP_HERO = "tophero",
}
